### ISSUE TITLE
Python Dependencies 

### ISSUE THREAD

**Issue by aidan-gibson** [A-J-F-Mackintosh/Mackintosh_et_al_2023_rearrangement_fixation#1]
Can you ensure the reproducibility of your python by posting the dependencies? Thanks!

**Comment by A-J-F-Mackintosh** [comment]
Hi,

All the python scripts require `docopt` and anc_sweep_simulator requires `msprime`.

I have added this to the README. I will close this issue, but if you have questions about a particular script then please open another.

**Comment by aidan-gibson** [comment]
Yep! I mean what _versions_ of the dependencies. If you used base python or venv this can be had via `pip freeze` (`python --version` would also be handy!) If you used a conda environment this can be had via `conda env export > conda_env.yml`. Thanks a bunch for publishing your code! This just ensures people in the future can run it as well.
